# Basic
title: 随便写写
subtitle: 网络备忘录
welcome_message: 
description: 互联网需要有记忆，应该有记忆，必须有记忆。
creator: <a href="https://mwy1992.github.io">@mwy1992</a>

url: "https://mwy1992.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: mwy1992
    # duoshuo: 
    
# Social
social:
    # weibo: onevcat
    github: mwy1992
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: mwy1992@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
